### ISSUE TITLE
Comparison of Emily Dickinson Projects

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#11]
The short poems of Emily Dickinson have generated lots of excitement and serious digital humanities projects in our time. Web technology lets more people than ever before view "photo facsimiles" of the tiny scraps of paper on which she wrote, and text encoding has transformed and remixed and circulated the poems to give them a digital rebirth. Let's review and discuss some of these projects to see what text encoding can do with the way we read a poet. 

Browse the following projects and choose two to discuss together in your post. You'll need to be patient and "dig around" some of these sites to get to the poems. I'll provide a little guidance to get you in to each one:

1. [Radical Scatters: Emily Dickinson's Late Fragments and Related Texts, 1870-1886](http://radicalscatters.unl.edu/) 
   * Skim around the introductions to get a sense of what this site is archiving. 
   * Then wander about in [the Browse documents](http://radicalscatters.unl.edu/browse.html): dig into a collection and select some poems: look at each reading view and look at the XML code.

1. [Emily Dickinson Project (fascicles 16 and 6)](http://dickinson.newtfire.org/) (made/remade by my students from 2015/16!) :-)
     *  Try interacting with some specific poems posted on this site, such as [Poem 1605](http://dickinson.newtfire.org/16/1605.html), and look at the [Dash Reduction Analysis](http://dickinson.newtfire.org/16/dash.html). What can you learn about how Dickinson a) wrote variations on her own wording, and b) how publications of her poems altered her work? How are you able to learn about this? 

1. [Emily Dickinson Archive: An open-access website for the manuscripts of Emily Dickinson](https://www.edickinson.org/)
    *  There are three ways to explore this site from the front page: either by Searching the text of the poems for a word or phrase, by browsing by library collection, or by Lexicon: looking up words and definitions pulled from Dickinson's poems. Try exploring some of each. 
    * For the Search box, try plugging in some words that jump out at you from the [Lexicon](https://www.edickinson.org/words). Suggestion: try the word "bee" or the word "fly"
   * If you look up the word "funeral" you'll see how this site archives versions of Poem 1605 represented in the Emily Dickinson student project. 

In your posts, you should respond with your thoughts about how any two of these sites compare with each other for 
a) how you interact with Dickinson's poems: how are they represented and what is the reading experience like?
b) what can you see of the text encoding: How easily can you find the markup, and what kinds of things can you see in the markup? How does the markup compare between the two projects you're looking at? 

This is a discussion! Since each of you is responding here, you can reply to each other, help each other out (it's tricky to to get a view of the code in the Emily Dickinson Archive but it is there!), and also feature examples (you can use screen captures from the sites in your posts). We'll keep this discussion running online until Friday this week.

**Comment by AliceR98** [comment]
The first website mainly focuses on Emily Dickinson’s original poems, as well as its transcripts. Meanwhile, the markup code is focused on identifying where Dickinson’s fragmented lines and words have been used for her more complete poems. I feel the markup makes this quite clear (though I still don’t know what the values stand for). The code also marks where stanzas begin and end, gives the poem itself a label, and marks down what kind of draft it is. 

Meanwhile, the second website shows the poems in its different iterations, as well as highlighting the changes the different editors made to Dickinson’s original poem. From the website’s comparisons, one can see that any changes made to the poem often involve punctuation, the capitalizations of certain words, and even having entire stanzas omitted. Reading the poem from the actual XML code itself is a bit harder as it is marking up four versions of the same poem at the same time. However, it is still clear that the markup code tags the differing words by labeling them with the same values they’ve given the different book citations.

**Comment by amayadwillis** [comment]
Emily Dickinson Project:
The poems are easy to find and there are several viewing options for them so that the reader can pick which edition(s) they want to view. You can view multiple editions at a time so comparisons can be made easier. 
The markup is easy to find, it is linked on the same page as the poem in a large box. Although I don't really understand most of the values, I can see that the lines are clearly marked and counted, and that the markup is well-formed. 

Emily Dickinson Archive:
The best way to find the poems is to search a specific keyword, which could be a little inconvenient if you didn't have one and just wanted to browse. The search box lists the first line/title of the poem, the date, and the edition. When you click on a specific poem it shows you the text on the right hand side and an image of the original text (if there is one) in the center of the screen.
To find the markup you have to be in the text box and click the "about work" dropdown and then "download as TEI" and open it.
The person who did the markup marked the stanzas and the lines, but didn't number them. The markup is pretty easy to read and understand, however, if you check it out in oXygen it says there is an error in it. I'll try to post a picture of the original error below. I tried to mess with it for a while but I couldn't figure out what the problem was or how to fix it. 
![digit](https://user-images.githubusercontent.com/70728138/92640682-a6345b80-f2ab-11ea-842f-1ff9751576fb.PNG)

**Comment by am0eba-byte** [comment]
Both the Radical Scatters and the Emily Dickinson Project websites offered very in-depth and organized analyses. In terms of easy navigation to the poem data content, the layout of the Emily Dickinson Project was much more navigable and very easy for readers to find and understand the content of the analysis of each poem. I also really loved how the student put the facsimile of the original documents and the text transcriptions of the poem right next to each other, and made it possible to toggle each of the different variations on a single poem according to publication. The color-coded highlighting of the individual differences in each line of the poem made it super easy to see how the poem was changed from one publisher to another, and I thought that was amazing.
![Screen Shot 2020-09-09 at 3 10 41 PM](https://user-images.githubusercontent.com/70165410/92642773-b69a0580-f2ae-11ea-92a1-2f3c67875811.png)
The Radical Scatters website was a bit trickier to navigate, but once I was able to find the analyses for individual poems, the data content was very clear and easy to understand. This website looked a bit deeper into some of Dickinson's poems that she scribbled down here and there, things that may not have been published but are extremely interesting to look at. They even organized their archives into all the different things she wrote on, down to the paper material, and whether she wrote it upside-down or not. For example, here is an interesting one of a fragment of a different poem she wrote, probably as a rough draft: 
![Screen Shot 2020-09-09 at 3 02 04 PM](https://user-images.githubusercontent.com/70165410/92643219-67080980-f2af-11ea-8371-b3e4da7a55ee.png)
and here is a text transcription of that document:
![Screen Shot 2020-09-09 at 3 02 25 PM](https://user-images.githubusercontent.com/70165410/92643265-7a1ad980-f2af-11ea-9d73-e9cb375e4204.png)
Pretty neat.

Because the nature of the documents being archived is so different, with Radical Scatters being mostly fragments and pieces of poems and the Emily Dickinson Project being mostly a comparison of poems in different publication contexts, the XML documents were extremely different. XML from the Emily Dickinson Project on each poem tended to be waayyy longer, because the student had to code for every single individual line or word variation for each publication context on each poem. It's actually super impressive. I give props to that student for having all that patience.
The Radical Scatters XML meanwhile, tended to be much shorter since they were mostly working with small fragment-like documents - but, they were also very interesting, because they went so far as to code all of the messy, hardly-legible little details of the hand-written paper itself. Here's code from the same document I screen captured above: 
![Screen Shot 2020-09-09 at 3 23 21 PM](https://user-images.githubusercontent.com/70165410/92643846-6d4ab580-f2b0-11ea-9bdb-53d9730a9b22.png)

**Comment by Emily-Levi** [comment]
The first Project: This project focuses on Emily Dickinson's late fragments and poem and also includes many photographs of her poems and fragments. to me the first site was a bit difficult to navigate. I expected a website that just listed all of Emily Dickinson's poems. finding the XML code for this project was a bit difficult. When I did find the XML code it wasn't that easy for me to read.In the XML code It seemed to me that there were a lot of href and class tags. 
      The second project: The style of this project website looks more simple than the first project. This project focuses on  transcribing and analyzing Emily Dickinson's poems. I noticed that finding her poems on this project is much easier than the last project. I also feel that getting to the XML was much easier on this project as well. I felt that the XML code on this project was easier for me to read. I noticed that in poem 602 there was a lot of PTR targets. Another thing I noticed with the XML code is that there were a lot of RDG tags. 
     Overall I feel that the second project was easier to navigate and that the XML code was clear and easier to find than the first project.

**Comment by N00000DLE** [comment]
**Radical Scatters:**
With this project they clearly have a set color scheme and a solid website plan. I really like how simply they laid everything out and how straight forward the site is. One critic is that I think it has too much text and I think it can be tough to read. Average attention spans are very low and I know that I do not have the attention span to get through all the text.
When looking through the markups you can see that the code is clearly good and it was fascinating seeing the code used for the website. It was easy to access the poems through the site, I went through and looked at a lot of the Document Fragments also because it was fascinating.

**Emily Dickinson Archive:**
For this sit I think that their home page is quite weird, when you hit about it takes you to so much stuff. The yellow text is also hard to read on top of the dark background, I think a slightly different color would have suited the site better. Overall though, the site is pretty easy to navigate and when looking through there is a ton of interesting things to explore.
For this one I also like looking at the scanned images in the manuscript view tabs. I tried to find the code but I honestly could not find it after looking for a bit, but I probably missed it in a very obvious place.

**Comment by BarbieCessar** [comment]
The first site I looked at was the Radical Scatters. Radical Scatters was pretty easy to navigate. It gave a nice introduction so that I was able to understand the fragments that the site was achieving. After reading the introduction I made my way over to the documents and looked over some of the poems. I liked this site because the poems were easy to find and navigate. It gave four different ways to view each poem. And it makes it easier to compare the original poem to the encoded xml poem. 

The second site that I looked at was The Emily Dickinson Project. This website also gave a helpful introduction that was easier to understand compared to the first website.Then I tried interacting with poem 1605. This site was extremely organized and interactive. My favorite part about this website is that you could pick a selection and it would highlight key words. Personally for me, this website made it  even easier for me to compare and contrast the different publishers. This website would be more helpful to hands on and visual learners. Overall, the distinct highlighting and interacting components were very user friendly and easy to comprehend.

**Comment by dxh405** [comment]
# Radical Scatters:
This site is an easy one to navigate. It is really straightforward in its goal and how it is presented. The introduction on the website is really helpful for people that are visiting. While looking through the website, I really enjoyed how the real picture fragments are implemented into the markup and description. Some of the pages are a bit lengthy in my opinion, but I guess it does add to the timeline type organization that he website is going for. I really like the description and amount of details I can get just from clicking on the poems. Makes getting basic info simple and quick. The color scheme is also something that works in the websites benefit. The Website is based on these old poems and the color scheme reminds me of that. 

# Emily Dickinson Project;
This site is really neat. The color coding of the poems really appeals to readers specifically like me. It makes it interesting for my eyes and my brain wants to connect the colors to what they mean. The website is also easy to navigate and find what you need. Interactivity is a really good thing if not overdone and this site does it really well. I do not get lost and know what I am looking at. I really like how you can look at this website at face value and get what you are looking for, but there is a ton of depth to it if you really want to dig your heels in and learn about a certain part.

**Comment by AtomicOlsen** [comment]
Emily Dickinson Archive:
For this website I chose to start searching common nouns, almost like a WebCrawler, starting with "dog" I started at the first line column and started to just look through what sounded interesting, I found for example that filed under multiple numbers and editions were the same poem, The B-version only contains the last two stanzas with no image, while the A-version contains the full poem with a photo. I found this interesting because nonetheless it's still an important part of her writing process and I am a bit of an e-hoarder myself, so things like this excite me. Unfortunately, I did not find any XML rendition on this website, maybe because it is made to be an archive and didn't necessarily have us text encoders in mind.

Radical Scatters:
Right off the bat I'm interested in the Transcription side, which are quite literally transcribing the letters into a typeface on white, it is interesting to see the kerning of these because -and this may be a shot in the dark- but I feel that the letter size of some of Emily Dickinson's poems has meaning. A711 for example, is 6 lines, 10 words, but the Facsimile shows that she sprawled this over an entire page versus perhaps centering it in a smaller font. I enjoy the ability to speculate on this that the Transcription and Facsimile has provided. (Side note, this website has broken scaling.)
The XML of these 6 lines is quite involved, I am interested to see that instead of hard-tagging her style, they've put it in a comment, hand=fair and ink=pencil. They have everything down to the letter no pun intended but quite literally, "rend="fair-copy, enclosed with letter (mailed)". They have self-closing line breaks and plenty of elements to boot. All around great site.

**Comment by zteyssier** [comment]
The first website I chose for my research was:  Radical Scatters: Emily Dickinson's Late Fragments and Related Texts, 1870-1886. 

Metadata is provided to describe the date of publication, the manuscript, the type of paper used, and more.  The color scheme on the website allows for a smooth enjoyable reading experience.  The markup is under the encoding tab on the website.  The XML markup contains line breaks (<lb> <lb/>) and differentiation for stanzas (-<ab type="stanza"> </ab>). http://radicalscatters.unl.edu/mss/a95-12.html?ref=file02   This approach has drop-down menus that provide more information such as the publication history and the commentary. 

There are lines of code associated with each poem on each page of the website.     

The second website I chose for my research was:  http://dickinson.newtfire.org/16/1605.html.  

Words, phrases, and hyphens are highlighted to illustrate the deletions or additions between each edition of Emily Dickinson's poem.  The reading experience is interesting since the actual manuscript and the new edition is side by side.  The highlighted words, phrases, and hyphens can make the reading distracting and frustrating.  This a completely different experience from the first website.  The XML markup is easier to find on this website.  The XML markup can be found on the gray "View Original XML" button on the left side.  This XML code is longer and more complex compared to the first website.  There are list tags with target attributes that reference image addresses.   
![XML-website_02-DIGIT_110](https://user-images.githubusercontent.com/70618741/92852885-3615fa80-f3bd-11ea-9e70-8e81449d2ea8.PNG) 
This code takes longer to parse through, however, the code is definitely robust and serves its purpose for the site.   

There are lines of code associated with each poem on each page of the website.

**Comment by Cameron-Bigi** [comment]
The first website that I picked was Radical Scatters. It's an all around good and easy to navigate website. The introduction is super helpful for anyone who is new to the site and trying to navigate it and showing the picture fragments. It is also pretty interesting to find out that the picture fragments are implemented into the markup. I also really like the look and feel of this site, makes it really pleasing to the eye and helps to keep my attention for long periods of time. 

The second website that I picked was the Emily Dickinson Archive. Like the last website this one also has a very good color to it that makes it pretty easy to read. The home tab and the about tab are very helpful in show people how to use the site itself and what's exactly on the site. It offers picture scans of all of the documents that are organized by the source that they come from. It's a very interesting and cool way to show the uniqueness of each document.

**Comment by Beeplosion** [comment]
The first site I looked at was the Emily Dickinson project, and it was interesting and helpful the way the students formatted everything to make it as clear and understandable to follow for other viewers such as I. I really appreciate the side by side comparison and having the choice to view the differing versions as well as the xml is a very nice touch.
The second site I checked was The Emily Dickinson Archive which takes a much different approach clearly. I appreciate the interface which allows the viewer to search a poem, or definition by word, but as far as I can tell it only allows high quality let only scans of the original posts which may be a bit difficult to read without a typed transcript like the first.

**Comment by argynarg** [comment]
Radical Scatters: It's interesting to see XML code that takes up so much more space than the text that's being encoded. While the fragment of text may only be 2 lines the XML could be a whole 20 containing information about the fragment, noting things that are in the fragment or were added after. For instance noting dividers in the text to break up lines to better keep track of the writing. 

Emily Dickinson Project: It's interesting to see how in the actual text of lines in many of these poems the XML can split a line apart into many sections, with single words within the poem taking multiple lines. I mainly saw this in corrections to words, where one line of XML would note what was actually written where the next would say how it would be written in proper format. For instance, in poem 601 the world explore is capitalized mid sentence, one line of XML noted the original "Explore" while another corrected it to "explore". It's fascinating how much a poem can be broken down word by word using XML.

**Comment by alexvanwoert** [comment]
On Radical Scatters, I was able to find the poems with relative ease and four different viewing options were available to me. I had plain text of the content, a facsimile, transcriptions, and encoding of the poem. The encoding option opened a new window with the XML file in it. The encoded file organized the poem by stanzas as well as lines. There was also a ‘seg’ tag that were used to indicate when Dickins hand wrote a minus or plus sign at the beginning or end of lines.
The Emily Dickinson Project had graphical analysis to compliment the poems. They showed the percentage of dashes and lines removed by publications in comparison to the originals. They also showed a network analysis to convey the changing variants of the poems from publication from publication. The XML was tougher to find than the first site, but I eventually stumbled upon a link to GitHub. In the linked repository I was able to look at XML files for each of the variants.
![Capture](https://user-images.githubusercontent.com/55804658/92866597-b5abc580-f3cd-11ea-8151-a559f8593754.JPG)

**Comment by wdjacca** [comment]
Radical Scatters was so much easier to use and user-friendly in a way compared to the Emily Dickinson archive. 
Personally, I liked the coding of Radical Scatters more as it is closer to what I would've coded myself. There were some tags that I was unsure of the actual meaning but it did not interfere with my understanding of the code and its structure.  Another issue would be how difficult it was for me to find the codes in the Emily Dickinson archive. Maybe this caused a predisposed advantage for Radical Scatters' code because it was so easily accessible and gave me a much easier time on the website. 

In addition, Radical Scatters also has more in-depth categorizing for its documents which make it very convenient for readers to search according. The Emily Dickinson archive, on the other hand, requires readers to actually know what they are looking for and have a clear aim in order for them to be able to find the exact code they are looking for, which while it is helpful for English major students, can be difficult for most people to navigate.

The one thing I appreciated about the Emily Dickinson archive is the lexicon function. This function shows the level of detail the makers of this archive put into the website, and it provides some context and insight into Emily Dickinson's word usage that may be beneficial for further research on her poems.

**Comment by natalyamyers** [comment]
## Radical Scatters:
This was a very easy site to navigate as most people who visited it have mentioned. I enjoyed how they had pictures of fragments of letters, and how the presented everything. However, there were several places in the pages I visited that just had an overwhelming amount of paragraphs and text, and for me, making it not so reader friendly. It took me a fair amount of time to find the code, but once I did it was easy to interpret and understand.

## Emily Dickinson Project:
It was interesting to just see the sheer amount of code on this site. I really enjoyed seeing the typed poem next to the picture of it and seeing the relation between the boxed words on the picture with the highlighted words on the typed up version. I also liked being able to see different versions of the poems and being able to view those differences side by side.

**Comment by ebeshero** [comment]
**Remediation** is the method that all these projects have in common.

**Comment by amw6765** [comment]
# Link 1 
The first website allows you to browse through a directory of folder like clusters in order to find what writing of Dickinsons' that you are trying to look for. It is not very interactive and hands on. The site gives you a picture of the original document as well as the physical description of the document. Also, it shows you a markup text translation version of what is on the original. While looking at the text provided to you by the website you can see the use of tags at the beginnings of paragraphs. These tags seem to state where and which part of the writings you were currently reading. The markup however, does not seem to be thorough and detailed.
# Link 3
The third website that I browsed was the open access site for the manuscripts from Emily Dickinson. This site just like the first one was fairly simple in what you're able to do with it. It gives you a linked directory to all the different locations that these various works are being kept at. From there, it allows you to look at virtual digital scans of the original documents. Because of this you're able to zoom in and out looking at the details of her true hand writing. On top of this it gives you more of a realistic and educational view of these works. There also is a search engine on there that allows you to narrow your results down to pinpoint a more direct path to the reading that you may wish to view. In regards to markup I did not come across much, if any at all. I was not able to come across any tagging or bracketing within this site. Unlike the first link there is very minimal markup to come across on this webpage. It is more hands on compared to the first.

**Comment by Joelpie** [comment]
Radical Scatters is a vast collection of bits, pieces, and full pages of Emily Dickinson's work. It's extremely in depth in its organization, with certain categories titled "Document was cross-folded" and "Document contains glue or paste residue". Individual documents are transcribed, and are also categorized by characteristics like folds, media, and penmanship. This makes the experience of browsing the website a little overwhelming, which is emphasized by the apparent lack of a search bar. However, the XML code is easy to find for each document, and contains standard tags we've used, most notably <lb/> for each line break.

Emily Dickinson: Fascicle 6 is a smaller, but no less in depth collection of poems, which emphasizes the differences between different printings of Dickinson's poems with the original writing. The menu bar makes navigation easier than Radical Scatters, and once again the XML code is easy to find. The code contains more tags, and more general structure as a result, which creates a more complicated appearance. This site also uses graphics to illustrate motifs found among Dickinson's work, though the Data Usage graph is a bit hard to read due to the small lines and multitude of colors.

**Comment by san5281** [comment]
**Radical Scatters:**
This website is very concise and makes the poems the center of the topic. The XML coding focuses primarily on the stanzas and their placements. All it takes is a single tab to view just about everything you want in a poem: you can easily access an easy to view "standard" version, the facsimile, the original papers, and the XML coding. It is very transparent and I view that as a positive.
**Emily Dickinson:**
The fascicles had the same amount of variants to read as the previous website, including the XML coding. However, this website was far more focused on specific keywords, as they were clearly highlighted. While this can be a con for longer poems, as the colors sometimes hurt my eyes, it was extremely useful for smaller poems and allowed me of understand the poems in a way I previously haven't thought of.
