### ISSUE TITLE
How to make <text> an element for ng schema?

### ISSUE THREAD

**Issue by AliceR98** [newtfire/textEncoding-Hub#13]
the goodMorning.xml has a text element alongside the source element, however trying to type it into the relax ng automatically colors the word blue. Is there a way to stop this from happening in relax ng, or do I have to change the element name in the .XML file? 

![image](https://user-images.githubusercontent.com/56094017/93142733-9bffcc00-f6b4-11ea-81bb-b6bbc0d5afd2.png)
![image](https://user-images.githubusercontent.com/56094017/93142806-bf2a7b80-f6b4-11ea-9b72-84ec4e5ed8e1.png)

**Comment by ebeshero** [comment]
@AliceR98 Excellent question, and thanks for the clear visual aid of your screen shot so others can see the problem! Yes, there is a way around this. Let me explain:
 `text` is a reserve word in Relax NG, so you'll get an error if you write rules like this:
```
xml = element xml {source, text}
text = element text {...}
```
The problem is that `text` as you point out, turns blue and means literally a string of text inside an element. But we now have an element *named* text. What we have to do is *escape* the reserve word when it is a label, using a `\` character in front like so:

```
xml = element xml {source, \text}
\text = element text {...}
```
The word will still turn blue in oXygen, but you'll see it be treated as a legitimate pattern to be defined if you use that syntax.
