### ISSUE TITLE
problem with xml

### ISSUE THREAD

**Issue by Kennaab** [newtfire/textEncoding-Hub#16]
<img width="1440" alt="Screen Shot 2020-09-20 at 4 04 47 PM" src="https://user-images.githubusercontent.com/70358707/93724842-a7516c80-fb78-11ea-883e-141f8ac7e022.png">
 
so I'm not sure what really happened here. because everything was fine and then I went to refresh it and it messed everything up

<img width="1440" alt="Screen Shot 2020-09-20 at 7 39 23 PM" src="https://user-images.githubusercontent.com/70358707/93724897-01eac880-fb79-11ea-9d33-8de495838876.png">

**Comment by ebeshero** [comment]
@Kennaab It's actually better that you're seeing these specific little errors, because it means your schema is now working! Before there may have been a syntax error over on the Relax NG, but you've corrected it now, and the schema is working. So, now you need to fix the schema so it validates your XML. You want to go step by step through each error you see, and figure out what you need to revise in the schema so it represents what you need it to. Probably you only have a few things to fix!

**Comment by ebeshero** [comment]
@Kennaab Start with your the error on your `<intro>` element. Why is text not allowed there? In your schema, does your rule for intro allow for text?

**Comment by ebeshero** [comment]
@Kennaab Isn't your `<para>` element really mixed content? How should you code for that?
