### ISSUE TITLE
Crowdsourcing Transcription: Issues, Examples, Reflection

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#17]
- Post your screen captures showing what you transcribed or reviewed or attempted, and reflect on your experience with crowd-sourced transcription here.

- What interesting information or leads for further research could you identify? 

- What questions and issues can you identify with the transcription process? What issues do you think project organizers might have with reviewing and correcting transcriptions?

**Comment by am0eba-byte** [comment]
This is my attempt to transcribe page 201 of 238 of Williamina P. Fleming's Variable Stars; Spectra #3  for Project PHAEDRA in the Harvard-Smithsonian Center for Astrophysics crowdsourcing website. I chose this document because it seemed one of the least complicated of all the available pages in the journal, and somebody had already done a lot of the transcription already, but they left out one section and noted in the "Notes" section that some of the text insertions needed to be edited and added. 
![Screen Shot 2020-09-22 at 10 11 04 AM](https://user-images.githubusercontent.com/70165410/94012345-ab4add80-fd76-11ea-86e1-b3012b9fc9bd.png)
I edited all of the text insertions that the previous contributor did not finish by wrapping the red-ink insertions on the text with ``` ^[[insertion]] ``` as per the transcription instructions, and added insertions that the previous contributor missed. This was a bit tricky, but once my eyes adjusted to all the numbers and the workflow of the transcription, it was easy enough. I can't imagine easily being able to do this if I had dyslexia!
![Screen Shot 2020-09-22 at 10 23 01 AM](https://user-images.githubusercontent.com/70165410/94013021-7f7c2780-fd77-11ea-9345-2fbe156d85a3.png)

 The part that I went in and fully transcribed myself was the last "Plate I" section, which was easy since I had lots of examples to work off of and there were only two lines of data to transcribe for it. To indicate areas where data was crossed out and replaced, I put ``` [[strikethrough]] crossed out data [[/strikethrough]] ``` followed by the replacement data that was inserted with red ink: ``` ^[[inserted data]] ``` There were parts where the inserted data was crossed out and replaced with another insertion, so I had to wrap the entire insertion with the ``` [[strikethrough]] ``` pseudomarkup. As I stated in the "Notes" section, the last line of data was difficult for me to read because the document identification data that the Smithsonian put at the bottom of the page was covering the text, so I did not transcribe it - that might be an issue that the organizers have to deal with to make the document more translatable to contributors.
![Screen Shot 2020-09-23 at 8 10 59 AM](https://user-images.githubusercontent.com/70165410/94015589-14cceb00-fd7b-11ea-8af2-85b52aee8baa.png)


I am not a mathematical person in the slightest, and although I do love astronomy, I had absolutely no idea what this journal was documenting. It seemed like letters and numbers of indication followed by simple math problems that were fixed many times. In the "About the project" description of the journal, it tells me that these journals were written by Williamina Fleming, who discovered 310 variable stars including the very first white dwarf star ever discovered. She did this by studying glass plate photographs of the night sky, and the entries are catalogues of stars, interpretations of stellar spectra, and measurements of vast distances in space. 

It's interesting to think about how astronomical data has changed over the years, going from data journals like this that had to be written entirely by hand, to fully-technological data that is much easier for astrophysicists to easily document and correct using whatever software astro-people have available to them these days. I'm sure further research on this could produce interesting data on human error while studying the universe - obviously, even without technology to easily identify mistakes, Fleming was still able to make over 300 stellar discoveries, including the discovery of the first white dwarf, which is astounding! I'm sure recent technologies might make this number seem small, but it's still absolutely amazing to me that she was so successful in tracking the vast universe just by using photographs, glass plates, and her mind.

**Comment by AliceR98** [comment]
This is my attempt to transcribe page 113 of 261 of the Freedmen Bureau's North Carolina's Field Offices' unregistered letters. I chose this one because it was very short and there was no transcription work done on it aside from a single `[[strikethrough]]` left by someone else. It also looked like a fun enough challenge.

![image](https://user-images.githubusercontent.com/56094017/94082845-d6ade680-fdcf-11ea-8a05-74290e48be7f.png)

I edited it by adding all the words I could make out. It was a bit challenging as my cursive reading has always been rusty, and the type of stylized cursive writing used in this document wasn't helping make things easier. It took me a while to decide one of the words was "Edward" because I initially thought there were three D's until I zoomed out a bit and realized one of them was just a W with the same stylistic swirl. As per the transcribing instructions, I also wrapped words that were struck through with a `[[strikethrough]]` and `[[/strikethrough]]' as well as marking any words I cannot make out with a `[[?]]`  and any word that I feel was a guess with a `[[word?]]`. I actually got really tripped up on the word "execute" because when I first looked at it, I thought it meant that, however I couldn't identify all the letters that would make up that word, so I was very indecisive as to whether it was truly the word "execute" or not. I was also very confused about some of the surnames, such as the one I guessed to be Philpott and another that I still couldn't make out. I guessed Philpott because I ended up googling a close approximation of that name, and found out that Philpott was a more common and well known surname, as well as one that best fit the group of letters on the document. I had also decided to mention that fact in the notes. In the end, what I managed to do to try to solve this was cross reference the names with other letters that were already pending review or completed, and I've found that others have also transcribed the words to be "execute" and "Philpott", though I have yet to find enough transcriptions of the third unknown surname, and the ones I've found had different interpretations of the possible spelling. 

In all honesty, if there is one thing I do wonder about, it's how the official transcriptors decide which is the correct spelling if different documents write up different interpretations of the same word. 

The next document I transcribed was page 212 of 261 of the same project. This was one I had actually started myself.

![image](https://user-images.githubusercontent.com/56094017/94082779-b7af5480-fdcf-11ea-9635-aab5c4e22f14.png)

This was an easier one to transcribe as the printed letters and cursive were a lot easier to read, though I did have trouble transcribing the handwritten cursive. The one thing that really tripped me up was the large inkblot that was redacting a word or two. This was simply because the rules didn't exactly say what to do when a document full on redacts a word rather than crossing it out in favor for another word. In the end, I improvised using a `[[crossed-out]]` along with a `[[?]]` but I'm still not sure if that was the way to do it. I decided to make the issue known in the transcription notes.

**Comment by BarbieCessar** [comment]
<img width="1219" alt="Screen Shot 2020-09-24 at 1 51 15 PM" src="https://user-images.githubusercontent.com/70769716/94181452-82594400-fe6d-11ea-9068-8dc8381be6f1.png">


I able to identify that the letter was going to Rockingham County NC. At first I had it mis-spelled but then I looked it up on Google and figured out the location and the symbols after it were NC and I was able to put the pieces together. A also could not figure out the persons last name because the writer had scratched it out. 

I had issues reading the cursive. I learned cursive in second grade and never used it since. I feel like it is a text that is outdated now of days. If project organizers are in the same boat as me, correcting transcriptions would be very difficult; especially if the writers handwriting looks like chicken scratch.

**Comment by amayadwillis** [comment]
I chose which document(s) to transcribe by simply clicking the first document that didn't include a different language. I ended up working on a collection called "Harold E. Morehouse Flying Pioneers Biographies - Conover, William." I was surprised to see that it hadnt been worked on very much, because all of the documents were type-written (with a few phrase corrections written by hand). It was very easy to transcribe, so I ended up doing several of them. 
I started with page 7 of 29  (below) and worked my way down from there.

![1](https://user-images.githubusercontent.com/70728138/94200306-323bab00-fe88-11ea-932c-a7156c8ff68f.PNG)

I didn't have any problem with it, the only thing I wasn't sure about was that a couple pages had things written in the margins and I didn't know where in the transcription to write them.

**Comment by Kennaab** [comment]
Crowd-sourced transcription I can definitely say is very hard to read. Especially due to the fact the documents look very old and are worn out. They are also in cursive or very small handwriting. 

As you can see, the pages look very dirty and like they have been through a lot. It adds more character to the context of the writing.


<img width="530" alt="Screen Shot 2020-09-22 at 12 04 29 PM" src="https://user-images.githubusercontent.com/70358707/94203986-69ad5600-fe8e-11ea-9963-cfa2bc59f448.png">

<img width="271" alt="Screen Shot 2020-09-23 at 12 02 59 AM" src="https://user-images.githubusercontent.com/70358707/94203979-63b77500-fe8e-11ea-97eb-c07b615ddf45.png">


 I’ve noted that I am not really a big fan of how they have the zoom option for some reason. I feel like it’s more complicated than the normal zoom and drag because you have to use the buttons at the top. Overall, transcribing seems pretty cool. It definitely could be something to do in your spare time if you enjoy transcribing old documents and figuring out what they mean.

**Comment by sxa585** [comment]
I chose WILLIAMINA P. FLEMINGS - REDUCTIONS OF PHOTOGRAPHIC OBSERVATIONS #9, I chose this as photography is something I have grown to be quite fond of, and digging into some of the old history and statics behind It i thought would be cool.
![Open surce](https://user-images.githubusercontent.com/70766190/94205796-045b6400-fe92-11ea-859e-beeff4e2ca10.PNG)

 I'm not sure as to how this could contribute to further research given how much the topic has advanced since the given time, but it is still cool to be preserved for the pure historical and cool value it gives. I mean they say if we don't remember history we are doomed to repeat it right?

It was interesting to find ways to show the things that you cant do with a keyboard, and trying to decipher handwriting you are not used to proved to be a challenge, I defiantly have more respect for people that do this all the time. Maybe if I knew cursive better it would go better

**Comment by zteyssier** [comment]
![Account-Ledger-Digit_110](https://user-images.githubusercontent.com/70618741/94211902-ae41ed00-fea0-11ea-9bfe-ec2668e77f5d.PNG)

The account ledger is in french, however, I have taken French classes in the past, so I can sort of translate some of the text.  The year is on the top left of the page, 1908.  The months are listed from March to July, November, and December.  The days are listed in the column between the red lines.  Feuille is a pastry in french.  I am guessing this is an account ledger for a restaurant
 or a cafe.     

![DIGIT_110-text](https://user-images.githubusercontent.com/70618741/94213733-a5074f00-fea5-11ea-974d-
77a9dc02ad6a.PNG)

I could identify other words with more time and the use of a french dictionary.  I would also try to use context clues to decipher the meaning behind the sentences.

How would you categorize specific notations?  Does translating the script to print, then from French to English make the transcribing process easier?  The challenging task would be to decipher or find a key identifier to organize all of the corresponding account ledgers and band records.  This could be a date, person, or place.  Different forms of handwriting from different people will make this organization process extremely difficult.

**Comment by wdjacca** [comment]
I tried to transcribe NORTH CAROLINA FIELD OFFICES, SUBORDINATE FIELD OFFICES: GREENSBORO, RECORDS RELATING TO COURT CASES, 1865–1868, PART 1 (PAGE 182 OF 300)
To be honest, I chose this piece because it had the least amount of non-legible writing. This piece was not difficult but the signatures still pose a challenge. The other pieces that I looked over were simply too confusing, which I think is the difficult part about crowdsourcing transcriptions. Looking at other pieces made me feel like I have never learned this language at all since it looked like gibberish to me. The transcribing process was fun and a little therapeutic though.

I've noticed that the person who started the transcription put both pages on the same line with no indication of it being two separate pages. I'm not sure if this is the general format but I think it would be much better to at least specify at the start of the new page. 

<img width="1552" alt="Screen Shot 2020-09-24 at 11 39 06 PM" src="https://user-images.githubusercontent.com/70660835/94224139-9c237700-febf-11ea-9bd2-f4ee560e219f.png">

**Comment by Cameron-Bigi** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/70741875/94232292-ae0f1500-fed3-11ea-84a6-5fdc1a76cdd6.png)
I tried to transcribe the document of NORTH CAROLINA FIELD OFFICES, SUBORDINATE FIELD OFFICES: HENDERSON, REGISTER OF LETTERS RECEIVED, VOL. 121, JULY 1867–DEC. 1868. This document was pretty difficult to read, the writing is very rushed and faint. This was also one of the only documents that I could find that didn't involve another language of some kind.

**Comment by Cameron-Bigi** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/70741875/94232787-bf0c5600-fed4-11ea-9b89-d42d57cd6d9a.png)
The document that chose to transcribe was the NORTH CAROLINA FIELD OFFICES, SUBORDINATE FIELD OFFICES: HENDERSON, REGISTER OF LETTERS RECEIVED, VOL. 121, JULY 1867–DEC. 1868. This is a very old and very hard to read document. It talks about a series of letters sent by many different people. The writing in this doc is very rushed, which makes the sentences hard to read half of the time.

**Comment by alexvanwoert** [comment]
![Capture](https://user-images.githubusercontent.com/55804658/94277947-4202d000-ff18-11ea-9504-526b84205d6e.JPG)
I transcribed a page of the NORTH CAROLINA FIELD OFFICES, SUBORDINATE FIELD OFFICES: HENDERSON, REGISTER OF LETTERS RECEIVED, VOL. 121, JULY 1867–DEC. 1868. These letters were written in sloppy cursive and made me appreciative of anyone that has transcribed documents so I do not have to read the original copies. There were a couple of words I was not able to make out including some names that I did not find on the supplied reference list. I was able to use context clues and go back in to decipher words I had trouble with initially after I transcribed the entire document. I assume the reviewer and project manager are seasoned veterans in deciphering discernable handwriting and will have little problem fixing my errors.

**Comment by amw6765** [comment]
<img width="1440" alt="Screen Shot 2020-09-25 at 10 22 52 AM" src="https://user-images.githubusercontent.com/70722523/94279780-96a74a80-ff1a-11ea-90c7-4b4bc9331dc4.png">
I attempted to try and transcribe this document but fell pretty short on doing so. Most of, if not all of the words that I was able to understand have already been "transcribed" by others. This document turned out to be a letter written by a gentleman and was addressed to another man. This letter states that the decision of Isaac was fair and just, and was decided by the military authority of the Court. Mr. Borne being at the time the singular appointee of the military authority at Raleigh. This letter was difficult to read because the cursive is very shallow and not defined. Personally, I am proudly proficient with cursive reading/writing but even with the knowledge I have, it was impossible for me to read this letter. I am sure with much more time and resources that I would be able to have a better chance of understanding this gentleman's writing. In being able to look and browse through these transcriptions, you can see the sheer amount of work and patience that these transcribers but into these various documents. This looks to be a, "practice makes perfect" kind of a thing. We might not be able to transcribe at first but with time, effort, and an open mind, Im sure we all can!

**Comment by bwm5473** [comment]
What questions and issues can you identify with the transcription process?
I attempted to review a transcription for _The Freedman's Bureau Paper_, specifically page 131. Unfortunately, the paper ended up being 93% done, and in need of a review for a few portions of it.

![Screenshot (47)](https://user-images.githubusercontent.com/70763198/94284606-9e69ed80-ff20-11ea-8080-32a74fe36297.png)

One main issue for me, and perhaps anyone else reviewing and correcting the transcription would be the eligibility of the document; not only was the handwriting to extremely stretched, which made the paper more difficult for to read, but the ink used in the writing starts to look blotchy in the first half of the paper.

**Comment by Emily-Levi** [comment]
I did the transcription for JB/143/024/002
![transcrpit](https://user-images.githubusercontent.com/70732867/94318583-d7bd5000-ff56-11ea-897a-2b5a5a8ea302.PNG)

![transcrpit2](https://user-images.githubusercontent.com/70732867/94318749-34206f80-ff57-11ea-9ad5-534f9bdb0565.PNG)

I found that finding a transcription that I could do. A lot of the ones I found I couldn't read the handwriting. I defiantly think an issues with transcribing is not being able to read cursive handwriting.

**Comment by N00000DLE** [comment]
![Capture](https://user-images.githubusercontent.com/60856407/94366308-50cabd80-00a5-11eb-9959-04cdeb267a0d.JPG)
So, my main issue with this was figuring out how to read and set up the transcription form. My document has 2 separate tables going on in one page and on top of the has strike-throughs and red writing over a lot of it. I was not really sure how to input a lot of the table and I did not want to mess it all up. I read the instructions but it did not cover everything I had to handle in the document that I picked. I think the hardest parts were finding documents that I could first read and then find something that I believed was in my scope of transcribing. Looking through many documents I settled on one with table but I did not realize how much stuff was going on inside them.

**Comment by argynarg** [comment]
Upon first working on the transcription it was very intimidating. A centuries-old document that I could barely read half of, and some of the letters I could read formed words that I had never heard in my life. Though being confronted with a page of cursive that I could barely read and the word affidavit, I began work on filling in what I could. It felt embarrassing at first not being able to transcribe half of the page, and I felt for a moment as if my work wasn’t helping at all, but then I realized that’s the point of crowdsourcing. Maybe, just maybe, some of those words I could fill in would be words that would stump other transcribers, if nothing else it would give them a start to work with. 
	As far as pseudo-markup, I really only used two forms, I entered a [[?]] anywhere that had something that I couldn’t figure out what it said, to make it easier for the next transcriber to pick up where I had left off. I used pipes to separate the columns of the form, as well as a comment at the top noting the format of the document in double brackets. One place that I was unsure of whether or not to add pseudo-markup was on the final entry, that was unnumbered. For readabilities sake this would make it easier to search for the 4th entry, however; I felt it wasn’t my place to add pseudo-markup there for it as I do not know this page’s relation to others, and I figured there was a possibility that it would interfere with the order somewhere else. For instance, if the next entry continued on with the number that should have gone into the unnumbered entry.
	As I got farther into the document it dawned on me just how much could be done with very little knowledge, even someone who could not read much of the text could still put in a basic framework with entry numbers and dividers and comment on the format to help the next person to come along get started with the document. 
![image](https://user-images.githubusercontent.com/69773455/94391904-c4f87600-0124-11eb-86b0-7d63187585dd.png)
![image](https://user-images.githubusercontent.com/69773455/94391912-c9249380-0124-11eb-9c8a-a47426a6c90f.png)

**Comment by Joelpie** [comment]
I took a bit of a different path with this assignment. The written pages I looked at were very difficult to transcribe, and I felt that I wasn't putting forth a decent amount of transcription. I did a bit more digging, and came across audio logs that also needed to be transcribed, so I decided to try my hand at one of those.
This screencap is taken from one of the Faris and Yamna Naff Arab American Interviews- Selma Salhaney, Thomas and Letefee Cory, 1962 July.
![Capture](https://user-images.githubusercontent.com/60297307/94445551-90f97100-0175-11eb-873f-6fa8023df784.PNG)

This was an interesting log, because the majority of what's spoken is in Arabic, with specks of English sprinkled in here and there. However, it's not just voices and words that the Smithsonian wants you to record. Any thumps or any other distinct noises are important to make note of, for the sake of thoroughness. It was difficult to keep track of exactly who was speaking at any given time, as the speakers were speaking over each other during some almost heated discussion segments. This was loosely solved by using the tag [Cross Talk], I borrowed this tag from another audio log I looked at.

In terms of questions regarding this process, I'm most curious on who does the verifying of the transcriptions. What credentials do they have to be in a high position to make the final decisions? Are they actually Smithsonian employees? I think the website explains this briefly, but something to humanize these mysterious editing overlords would be nice. There's also the issue of things that are borderline unreadable. Like I said earlier, some written documents looked rather tricky, and some looked difficult to even decipher a word (not to mention the one written entirely in French, non, merci). How are these tricky tablets unscrambled? It'd be really interesting to watch a livestream with some collaborators going through and picking apart these files.

**Comment by Beeplosion** [comment]
From my experience, I had a lot of trickiness trying to attempt to get through what I could. Many of the ones that seemed doable funny enough kept getting taken and by the end of the weekend nearly everything was at 90% done aside from a select few. I decided to look on through for a while to see any other tricky ones I could at least attempt on. I was curious why a few were so low a number of attempts until I realized the difficulty that comes with the language barrier. The audio was mainly in Arabic, and the first couple of tests were in French and cursive so a double whammy for me. The one I got the farthest in understanding was this 3rd number document, but I had trouble due to the sloppiness of it at times. I tried to write notes to help the next person to attempt it as things such as random dots that could be smudges or actually decimals could really impact the information depending on what they are transcribed as.
![Screenshot (827)](https://user-images.githubusercontent.com/70736586/94448444-e71be380-0178-11eb-8149-bb3c228f910d.png)
![Screenshot (828)](https://user-images.githubusercontent.com/70736586/94448447-e7b47a00-0178-11eb-95e9-43e6c21bada4.png)
![Screenshot (829)](https://user-images.githubusercontent.com/70736586/94448450-e84d1080-0178-11eb-88fc-24fbc32ab8b7.png)

**Comment by AtomicOlsen** [comment]
I often have a particularly hard time reading someone else's writing, so this assignment was rather difficult for me, through tech issues (why not allow users to add an email address to their account after the fact if it is required for editing?) to the actual writing, I found myself doing less transcribing and more reviewing on the Smithsonian site, 
![GluikaFirstSikArr](https://user-images.githubusercontent.com/55807185/94448902-7628fb80-0179-11eb-8729-104c86f07e7f.png) Reviewing was great because it enabled me to contribute without risk of really mucking things up. This page was relatively easy to read and the math portion came easy as well, it was easier to spot mistakes (of which i found none) when I could reference them back and forth, I also suppose that when you're working intensely with one author, that simply reading the transcription side by side as well as reviewing can fine-tune your eye for the individual's handwriting. Great stuff!

**Comment by JoshSige** [comment]
This subject matter seemed very interesting to me as I know nothing about the legal status of slaves in post-war America. The first thing I noticed was the intricacy of the handwriting in this document. That is the first issue I faced when attempting to transcribe this. I don't think anybody can definitively decipher exactly what was written on this page, however, I think a good, educated guess can be made. 
![Screenshot (88)](https://user-images.githubusercontent.com/72031020/94449678-5b0abb80-017a-11eb-8de1-2757ce6daaa5.png)

I came across the same issue towards the bottom, as none of the signatures were readable, at least to me. I just really had an issue definitively saying what was written open the page if it was handwritten. 
![Screenshot (89)](https://user-images.githubusercontent.com/72031020/94449693-60680600-017a-11eb-9101-711dc971956f.png)

**Comment by dxh405** [comment]
I started out by looking specifically at Archives of American art and went through several pages before finding out that they had all actually been completely archived! I find that to be pretty cool as there was over 150 pages of different documents that needed transcribed. I then opened up my search to the theme of Art and Design and found that only one of them had not been completed. It is a French document, so I have no idea what it says, but I do know it is about the jeweler, collector, and author Henri Vever. 

![French](https://user-images.githubusercontent.com/70723878/94452663-c7d38500-017d-11eb-8553-fcc01ac21d1a.PNG)

Looking through many other different documents, I could tell that I would have a rough time transcribing a lot of them. I really struggle to identify letters and shapes in cursive. Its something I have always had trouble with. I do find the process of transcribing interesting. Most of my time was reading over a lot of what was transcribed and matching up what the transcription said to the images themselves. Looking at finished projects helped me get a bit better at identifying letters and words.
