### ISSUE TITLE
Puzzling Schematron Validation Error

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/textEncoding-Hub#32]
When I associated my Schematron file to the coins_change.xml and looting_soldier.xml files (with mindful file management in mind of course) I got a strange error that I can't quite figure out how to fix: 
![schematron_error](https://user-images.githubusercontent.com/70165410/100785480-b35e7380-33de-11eb-9ccf-23a04e3561c5.png)

I tried re-associating and messing with the namespace lines quite a few times, but that error just keeps coming up on both of the xml files. Help?

**Comment by ebeshero** [comment]
@am0eba-byte Ah! I should have mentioned this in class. Schematron needs to know that what it is reading is actually a number to do those comparisons. It is actually interpreting the `@lat` and @long` values as text instead of number information. (It's not recognizing that they are a numeric datatype, alas.) So, what you do is make sure it's being read as a number: wrap the the `@lat` and @long` in your tests in a `number()` function, like so: `number(@lat)` so your comparison test will be testing a number.
