### ISSUE TITLE
Crowdsourcing Transcription: Examples, Issues, Reflection

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#47]
- Post your screen captures showing what you transcribed or reviewed or attempted, and reflect on your experience with crowd-sourced transcription here.

- What interesting information or leads for further research could you identify?

- What questions and issues can you identify with the transcription process? What issues do you think project organizers might have with reviewing and correcting transcriptions?

Here's an example of a screenshot: You can drag and drop OR copy and paste the screenshot image file into the Issue window as you are typing here:

<img width="928" alt="Screen Shot 2021-09-22 at 10 05 50 AM" src="https://user-images.githubusercontent.com/4014518/134359325-5ccc6ec2-8cc7-4b44-a500-de4c99e95fed.png">

**Comment by ebeshero** [comment]
For those unfamiliar with taking screen captures, here is some guidance: 

* [Mac: 4 ways](https://www.cnet.com/tech/computing/mac-screenshots-4-ways-to-capture-your-macbooks-screen/)
* [Windows: 7 ways in Windows 10 and Windows 11](https://www.cnet.com/tech/services-and-software/7-ways-you-can-take-screenshots-in-windows-10-and-windows-11/)

**Comment by Tiny-Pickles** [comment]
My transcript was a historical document about North Carolina African American schools. I think we could markup the progression of civil rights with each series of these documents. For example school back in the early 1900's were a lot different then the school we see today. Most school were segregated at the time maybe these documents could be used to further research terms associated with race at the time and the progress of segregation.  One issues I found with the transcription is reading had written cursive. Also I think have a way to transcribe the location of the different headings and subheadings of the page would be helpful to represent the layout of the page.   

![Transcription-digit110](https://user-images.githubusercontent.com/60298734/134558439-547216d4-6d22-4df6-ad97-298eb3f8461e.PNG)

**Comment by arrowarchive** [comment]
When browsing through the transcriptions, the handwriting was nigh-unreadable to me. Thankfully, after enough time, I came across some journals and letters from World War II that were written on typewriters. The test was faint, but still legible. 

From what I could gather here, it appears as if soldiers had a hard time returning home in the last years of the war. This soldier in particular mentions boarding a ship in San Diego and later mentions Okinawa, making me wonder if he was stationed there. He hasn't received any mail, hasn't received any new clothes, and is desperate to return home to his family. After some research, he arrived nine months before Hiroshima and Nagasaki were bombed and the U.S military are struggling to get people home possibly due to the fallout, which has lasted nearly two months. It was interesting reading about a soldier's perspective around that time and being _so close_ to Japan.

![transcript1](https://user-images.githubusercontent.com/70866633/134568823-1df82821-bbd4-4a3f-b0f2-e6b82bdf3216.jpg)

<img width="941" alt="transcribe2" src="https://user-images.githubusercontent.com/70866633/134568842-9bf4142e-dde9-45ed-b718-a29028274859.png">

**Comment by austinmurry** [comment]
My document was a set of diary entries from a military soldier working in the barracks. As I was transcribing this typed diary, I was reading into what this man was writing about. This set of entries was about this soldier who was a little home sick and could not wait for his unit to be relieved come that November. He talks about what he did throughout those days and how her is using these journal entries as a type of therapy for the now and the future. He claims that he has a lot of great memories that he doesn't want to forget, and if he ever seems unhappy then all he has to do is read these journal entries and he will be jumping off the walls happy again. He also talks about his wife whom he loves and misses very much. Transcribing this was interesting and kind of fun as I got to take a look into what this soldier was thinking during the time he was writing these and I got the chance to turn these into more modern text.
<img width="1434" alt="Transcribe HW" src="https://user-images.githubusercontent.com/77990010/134587508-7915b469-986b-4068-bb01-7d4031980d46.png">

**Comment by Yuying-Jin** [comment]
![image](https://user-images.githubusercontent.com/62861214/134594680-38ba2213-f38c-4e3f-929d-d089d0eca716.png)
This document I transcribing is a letter written for map transaction. 
I find hand-written contents are difficult to transcribe, because most people prefer to write with swashes. I often cannot distinguish between b and l.  When I meet the name of person or place, I can guess what the whole word is according to several letters. The printed content is not difficult to transcribe, just need to be careful.

**Comment by sveludandi** [comment]
My transcription document was Iowa Seed Catalogs from 1883.  I thought this was interesting to read as this page shows comments from various customers. This page has already been transcribed by what looks to be some kind of software. This software picked up letters that were cut or miswritten and used symbols instead to look like the original. For example "we" was written as w;; because the e was a little faded on the original. There were also many other mistakes on the transcription, mainly symbols that shouldnt be there and mispelling/misinterpretatio
![Capture2](https://user-images.githubusercontent.com/66397253/134598993-f8bff5f6-9822-4411-8955-1c3d7ffc1354.PNG)
n.

**Comment by thammer12499** [comment]
The transcript document I contributed to was Celebrating 175: Louise Nevelson, Subject File, National Association of Women Artists, 1959-1965. The different transcripts I looked through were very clear and listed. Many of the pages I went through listed people I had never heard of before. I had an issue with previous contributors choosing to shorten the documented transcript rather than following its format as closely as possible before I was kicked off by another contributor. I thought it was incredibly strange how only a single person could contribute at a time.
![Screenshot (308)](https://user-images.githubusercontent.com/78119613/134599799-8e640b88-9aaf-4ab3-adef-7393b13069c8.png)

**Comment by erinmooney** [comment]
![image](https://user-images.githubusercontent.com/78123905/134604129-0ede7717-5888-4a79-8dcf-db42fc947d2c.png)


I think it is pretty cool how much collaboration is actually done on these! There are quite a few handwritten journals (like this one) that are almost completely transcribed. 

I am working on the James Carroll Beckwith, Diaries, 1873-1878. I would actually like to read some of the linguistic differences back then versus now. 

I think the issues that project organizers can have when reviewing and correcting transcriptions is if they too have no idea what a {{?}} word is. What if a word or phrase is way too much like of a scribble to comprehend? Will they just keep passing it on until someone figures it out? Or will they just mark it as unknown (until later identified (if it does get identified))?

**Comment by jbg5721** [comment]
As I was searching I found this document with Anglo-Saxons in the title and I thought that would be ancient and cool to try. I didn’t think about how that also means it wouldn’t be in any recognizable English. I found it interesting that I could identify letters. 
I eventually came across a Federal Census document from 1850. Pretty straight forward with a long list of various names. One issue I feel like I see with the transcription process is it takes a lot of time. A lot of people don’t really want to sit down for many hours and put in the needed effort for transcription. This is especially true for documents that are in a language that perhaps aren’t used anymore or it is in handwriting that is hard to read. 
![1C095296-8CB1-45D8-BF79-89F1778243D0](https://user-images.githubusercontent.com/78062156/134613458-ea2d8623-8f21-4ac5-9466-c18e2a94ab68.png)
![529AF7EF-A811-47AA-AC9E-5527EE8FDC7A](https://user-images.githubusercontent.com/78062156/134613468-fdf1ae09-30e6-41c7-9701-715607f5e782.jpeg)

**Comment by SCD5363** [comment]
![Capture3](https://user-images.githubusercontent.com/89928602/134620692-09a84a17-2914-4972-932f-502da9e6975b.JPG)

**Comment by ZakMurphy191** [comment]
<img width="1680" alt="Screen Shot 2021-09-24 at 5 24 28 AM" src="https://user-images.githubusercontent.com/89998845/134651884-d8354ab7-2b12-44ec-a1c9-31229fffa979.png">

I thought that this hw assignment was super interesting, and it was super cool to come across all the different papers from Alabama Department of Corrections records; Alabama Board of Inspectors of Convicts investigation and testimony, 1886. This was interesting because not only did I get to read the paper of what people have done wrong in the past, but I thought it was super interesting comparing our age to back then.This really gave me an eye opener for how much times have changed.  I see a possible project showing the comparison from todays age to back in the late 1800's and see first hand how different things were. It would be really cool to create a super cool website showing the differences in the centuries, to show others the differences.

The issues I had with this project was that the transcription was super hard to read, this little paragraph took me well over 2 hours to transcribe. Other than problems that I can fix like studying cursive I thought that this was super cool. I especially like how others proof read  your work and you can comment back and fourth with them about the transcription to ensure the page is correct.
<img width="1680" alt="Screen Shot 2021-09-24 at 5 25 11 AM" src="https://user-images.githubusercontent.com/89998845/134654218-4f543dd5-f3ec-4ed5-8db8-ab562020e7a7.png">

**Comment by Janman813** [comment]
![transcription](https://user-images.githubusercontent.com/70905616/134675145-57e4b69a-8646-4f12-b5ca-244da7627f49.png)
This project was quite interesting. As I was looking at the document it was a little hard to tell, but it became numbers and months which made it easy. the document that I worked on I think was someone's work long of either hour they work or money they made. but then again I do not know. This document I would have to look into more and find others that are similar and compare them to each other to find what it is truly portrayed.

**Comment by acc5763** [comment]
<img width="1440" alt="Screen Shot 2021-09-24 at 10 18 02 AM" src="https://user-images.githubusercontent.com/90055454/134690044-5280d390-378d-426a-a44b-c60b6f4d15fa.png">

My passage is from the book Poems of Cabin and Field written by Paul Laurence  Dunbar. It was really interesting seeing all the mis-spellings, being that it was written by someone who was not fortunate enough to go to School. This document was very easy to transcribe. However, a lot of the hand written ones are really hard. I start to transcribe a few of them but had a lot of trouble doing so. Thankfully, I found a much easier one.

**Comment by ericsandbloom** [comment]
![names names thats the game](https://user-images.githubusercontent.com/78065005/134700488-8ad5af46-1a21-4b0b-9859-bcd3708918db.png)

So the list itself was a bit hard to work with because aside from the column style, there wasn't a good numbering system. So it was often hard to keep my place. However, this could potentially be an example of the problems with people not learning cursive anymore. I could recognize names that were unique but because they were in cursive I could still read them. The list in the typing area was a bit messy. This kind of list would probably be best to go through with a spreadsheet, it's what it reminds me of the most.

**Comment by bealse18** [comment]
<img width="1440" alt="Screen Shot 2021-09-24 at 11 55 14 AM" src="https://user-images.githubusercontent.com/90015616/134707203-b996e0b5-5d72-4a8a-8369-c16d820cc994.png">

I was struggling to read the files with handwriting mostly because of the lack of context in some of them, I found the typewrite r files to be easier to transcribe but hopefully with some practice I can work my way up to the handwritten ones

**Comment by NickyV1234** [comment]
![transcribing](https://user-images.githubusercontent.com/70916831/134718545-632f845f-df8f-40a6-91cf-2f36e2b50931.JPG)
I haven't worked with cursive ever since i was 11 years old in 5th grade. I clearly need some practice but for the most part this was rather interesting to transcribe, some words I could look at and tell right off the bat what they were. also it helps to understand the  context of the sentence you are typing because that can also help you predict words that will be said which can help with interpreting the writing.

**Comment by Tiny-Pickles** [comment]
I transcribed another collection from the North Carolina archives, the Maud Hayes Sticks letters/transcripts.  As I was transcribing I noticed that the rules did not cover certain aspects of writing. For example they did not have a rule for adding hand written words or letters for transcription. They also did not have a rule for letters or words hand written on top of the type text as well. I believe that the main focus for transcription is to get the main text content across especially when it involves letters or drafts of novels. But I also believe that structure is important when it come down to focusing on poems or government documents. My final thought is I think showing discrepancies between revisions is important for the final transcription of the document and the rules for transcription should reflect that. 

![2ndTranscription](https://user-images.githubusercontent.com/60298734/134814662-ba9a44e7-a98e-47d3-bf6b-5aa033e59663.PNG)
 
![transcription-rules](https://user-images.githubusercontent.com/60298734/134814663-6dc296f4-449d-40df-9e05-e159d123ac7d.PNG)

**Comment by arrowarchive** [comment]
I transcribed another entry from the Carolina Archives. This time, I challenged myself to find some handwriting that was _somewhat_ legible and try to transcribe it. I believe this is part of a letter collection from the Civil War, and most of it was easy for me to understand. There were a few areas where I did not know what the words were, but it was easier to read than most of the letters I came across.

That said, I feel like a lot of older documents (especially letters) are written in cursive. It's bizarre to think about, since cursive has been all but dropped (with the exception of signatures) since I was in third grade. Was cursive widely encouraged over what we consider "print?" when did using "print" become more common? it raises some questions that makes me wonder why older documents (unless written on a typewriter) are harder to transcribe.

![transcribe 2 1](https://user-images.githubusercontent.com/70866633/134820137-aa8bf0e2-ebf3-42fc-89fc-25775f257087.jpg)
![transcribe 2 2](https://user-images.githubusercontent.com/70866633/134820139-6fe46a8a-be29-4472-aa28-f7827a99201b.jpg)

**Comment by erinmooney** [comment]
![image](https://user-images.githubusercontent.com/78123905/134822440-e47f1500-9db0-43f8-ab58-4116eb8732ac.png)

I picked this one because I am minoring in French and studied Italian in Behrend's Italian cultures class, so I felt like I could make fairly educated guesses on what the words on the clipping were. 

To me, the capitalization of some of the words was odd, but they seemed to be that way in the written text. While working on it, I was wondering if this kind of capitalization was common in Europe during this time. I thought it would be extremely important to follow exactly how they spelled different words because that might be an older way of spelling a word that I know (or think I know) to be different now. I like that about this set up. Because it is being reviewed and passed around, you just need to give your best, educated guess at what is being said and then someone else with better resources on the topic will review it. This set up takes a lot of pressure off of the transcriber to be 100% correct!

**Comment by austinmurry** [comment]
For this one, I tried to work with handwritten text. But seeing as I couldn't read most of it and haven't really had to since the 3rd grade, I chose to move on and continue with another typed document.

As I was going through this text I was trying to follow the rules played out by the creators of the page as best as I could, but sometimes it was harder than I had originally thought. They don't have a way to point out special character or different stylizations of words or sentences. The document I transcribed had a line dash through the middle to break the page, but due to the linear format of transcribing that the creator wants, and as @Tiny-Pickles pointed out, they just want the main text and contents of the document to be transcribed. My xml worked brain doesn't like this though and wishes there was a way to point out these different characters and stylization choices throughout our transcriptions. This could be a problematic thing though as those stylization characteristics are there for some sort of a purpose. So if you take those out of the document when we transcribe it, then overall you are in a way changing the document, which doesn't seem right...

<img width="1429" alt="Screen Shot 2021-09-26 at 6 19 41 PM" src="https://user-images.githubusercontent.com/77990010/134826651-09a80219-69d4-4d24-b544-5c62701263e4.png">

**Comment by Yuying-Jin** [comment]
Originally, I tried to transcribe a hand-written document, and then I gave up. The person who writes the document never considers if the document can be understood. Finally, I still chose a printed letter. This letter is about arranging a student's residence. The receiver was a student, and the student was noticed by home camp that after camp closing the student needed to go to Andover as planned, and if Mrs. Erving was not willing to take the student during this holiday, the student had to stay at the inn and bear huge expenses.

![image](https://user-images.githubusercontent.com/62861214/134828828-1fb2675b-6819-432b-9ec3-574053554c5f.png)

**Comment by luh429** [comment]
![FullyTranscribed](https://user-images.githubusercontent.com/78118867/134835436-f84a72e8-22b9-4ff7-9960-bcb67ab33e6d.PNG)
After a lot of searching I finally found a hand written document that I felt like I could transcribe. I got the document from the North Carolina site and even though it was short it was still difficult to describe because I struggled to read the handwriting and took me longer than expected. The document was a report from the city attorney.

**Comment by jbg5721** [comment]
I wanted to go for a bigger challenge this time around and, despite the handwriting not being too awful, and still being legible. I still cannot read script well. As you’ll see in my screenshot I had a cursive alphabet open right to the side. It was a hunt just to find the next letter for some of these words. The text is from a log book from the CSS Alabama. So of course there are a lot of sailing terms that I am not familiar with. After a certain point I stopped working on this, mostly because I just felt like I wasn’t even being helpful. Too many words were just becoming [???]. I added the second picture because I wanted to see what month any of you thought this was. To me it looks like Joniy, but we all know thats not a month. Given that this is a logbook, I would think the most important information is up near the top. So the bad look out at the mast. Looking at my screenshot while posting is making me realize that the writer wrote mast not mass. But I do know that the mast is tall center pole that holds all the sails. I could think that this could mean some sailer was not paying attention to the ropes and sails or if they were up high, they might not have been paying attention potential dangers.  
![36A4D542-7271-4205-A2A6-31D372DC7332](https://user-images.githubusercontent.com/78062156/134840323-256ae2da-4430-4672-8a07-543e723dc5c9.jpeg)
![99283BD5-9BAB-4710-B644-1852AA423DA9](https://user-images.githubusercontent.com/78062156/134840316-4262949f-cd70-459b-beaa-aedf169ba47d.png)

**Comment by Janman813** [comment]
![form](https://user-images.githubusercontent.com/70905616/134921772-6fa48581-4405-48db-9832-e45a60795fb4.png)
![Transcriptions part 2](https://user-images.githubusercontent.com/70905616/134921790-f94f7b43-7bb8-4199-8912-8e1d5e2c88af.png)
When going through this again and finishing the first page. I realized that it's not a work log but a tenet log for those who live in that apartment. I could not tell what the one word was at the top and the middle statement till going through again.

**Comment by hjl5363** [comment]
For this assignment, I decided to analyze the Ordinance of Convention that is from the articles of the United States Constitution. While the handwriting is okay, I still had some trouble with analyzing the document (I personally do not have very good handwriting or cursive reading skills.

Some questions that I ask myself when transcribing this document are how the document, in particular, should be formatted, particularly with pages, and the proper capitalization of letters. In addition, there are some special characters, such as "^" that I do not exactly understand the most appropriate course of action. Revisiting the handwriting, I do not believe that I could ever encode the handwriting on the bottom of the second page, particularly with the text that crumbled and on top of each other.

The other thing that I could see being an issue is that the way we speak, use grammar, and communicate evolves over the years, and it will continue to do so. Nobody was alive when this was written, so I think that there might be some difficulties that come up from there.

<img width="1380" alt="Screen Shot 2021-09-27 at 10 03 08 AM" src="https://user-images.githubusercontent.com/70916576/134924313-20ca3c93-4fa0-4744-9ffb-29eb66c6bfff.png">

**Comment by aidanvray** [comment]
> ![transcription](https://user-images.githubusercontent.com/78158447/134694547-35dacc6e-5036-411f-94f5-3a56cdbc7418.JPG)
> 
> I started transcribing a page from a draft of "A Trip Around the World". The draft is from 1910-11 and seems to be formatted as dated journal entries. The page I worked on was about the author meeting officials of the Japanese government. For further research I would like to learn more about the book itself, since from the single page I worked on I'm still not even sure who the author is. I would also look into what else the book covered and try to find out if it ever actually got published. My only issue with the process was that even after looking through the expanded list of guidelines I wasn't quite sure how to transcribe text that was written over other text.

**Comment by aidanvray** [comment]
![transcriptionComplete](https://user-images.githubusercontent.com/78158447/134928600-71097cbf-e6c4-44a6-8171-e60f46de9b08.JPG)

Here is my finished transcription from the "A Trip Around the World" draft. While working on it I encountered a couple more situations involving handwriting going over the typewriting, and the guidelines don't give a very definitive answer for how capture that. I also didn't like that the document had underlined text and mix of different types of writing, but the guidelines don't distinguish this.

**Comment by hjl5363** [comment]
For this Crowdsourcing Transcription assignment, I decided to try to transcribe a Colonial Court record. First, I ran into a ton of issues with the handwriting of the document, and I found it very difficult to read what was written. As I mentioned in my previous post, I think this is to partially blame for my poor cursive reading skills. I have historically not had very much experience trying to read this type of writing.  Another major issue that I can identify with this particular transcription is trying to understand what was written on burned paper and fully grasp what was written at the end of this document. I have personally never seen a document that has been formatted in this particular way, especially with something being written to the right of the signature. I also want to share that these two exercises have been very interesting for me to complete. They have really taught me the obstacles of encoding text, and some of the big ideas that come with it.

<img width="1380" alt="Screen Shot 2021-09-27 at 10 37 33 AM" src="https://user-images.githubusercontent.com/70916576/134930801-02fbea30-bd2e-4f44-ad64-e2e2f3733a61.png">
<img width="1380" alt="Screen Shot 2021-09-27 at 10 40 05 AM" src="https://user-images.githubusercontent.com/70916576/134930817-9935bcba-8647-4e24-9ca5-91cb4c66d3d9.png">

**Comment by luh429** [comment]
![Document3WithCircles](https://user-images.githubusercontent.com/78118867/134930884-5529dbc2-ceab-4f33-be80-cdf305c36424.PNG)
After a lot of searching I finally found a handwritten document that I felt I could possible transcribe. At the point of this picture I was not done and had skipped over a lot of words but one thing I found very interesting was how the writer makes his capital letters. A lot of his letters (for example the letter C) have a big round loop after them that really threw me off. Luckily I looked at the title of the document and picked up the pattern in his handwriting form the "Cs" in "Common City Council" and the when I came across other letters with the loop I realized it was just his style and not a separate letter. From context I also realized he writes his lower case "e" a few different ways which I found very strange. I went through and circled some of the capital letters from my screenshot for an example.

**Comment by ZakMurphy191** [comment]
<img width="1680" alt="Screen Shot 2021-09-27 at 10 53 35 AM" src="https://user-images.githubusercontent.com/89998845/134933105-35533e7a-a3c2-4c1e-949a-7be0775ea71e.png">
For this time I decided to work on a transcription for African American Education. when I am transcribing a page I read the page outlaid to myself to make sure what I think makes sense, with that information I read I run down the list of what? why? when? I do this because the information that is being interpreted needs to have the correct dates, slang, and what they were talking about. When transferring the important information to the text box it is really important to the data collectors that you write it exactly the way the person wrote it back in the day. Another big rule is to make sure if anything is crossed out to say that in the page where they crossed it out, along with all the other types like that. In all the most important role for my transcription was duplicating the paper to look exactly what the original form was. I had a lot of fun doing this I can't wait to hear what you all have to say!

**Comment by ZakMurphy191** [comment]
> <img alt="Screen Shot 2021-09-24 at 11 55 14 AM" width="1440" src="https://user-images.githubusercontent.com/90015616/134707203-b996e0b5-5d72-4a8a-8369-c16d820cc994.png">
> 
> I was struggling to read the files with handwriting mostly because of the lack of context in some of them, I found the typewrite r files to be easier to transcribe but hopefully with some practice I can work my way up to the handwritten ones

I totally agree with you it was very difficult to read some of the handwriting that the author of the text write. I think this has to do with how formal they write depending on the time frame, I also believe that it is super hard to read cursive.

**Comment by ZakMurphy191** [comment]
> I wanted to go for a bigger challenge this time around and, despite the handwriting not being too awful, and still being legible. I still cannot read script well. As you’ll see in my screenshot I had a cursive alphabet open right to the side. It was a hunt just to find the next letter for some of these words. The text is from a log book from the CSS Alabama. So of course there are a lot of sailing terms that I am not familiar with. After a certain point I stopped working on this, mostly because I just felt like I wasn’t even being helpful. Too many words were just becoming [???]. I added the first picture because I wanted to see what month any of you thought this was. To me it looks like Joniy, but we all know thats not a month. Given that this is a logbook, I would think the most important information is up near the top. So the bad look out at the mast. Looking at my screenshot while posting is making me realize that the writer wrote mast not mass. But I do know that the mast is tall center pole that holds all the sails. I could think that this could mean some sailer was not paying attention to the ropes and sails or if they were up high, they might not have been paying attention potential dangers.
> ![36A4D542-7271-4205-A2A6-31D372DC7332](https://user-images.githubusercontent.com/78062156/134840323-256ae2da-4430-4672-8a07-543e723dc5c9.jpeg)
> ![99283BD5-9BAB-4710-B644-1852AA423DA9](https://user-images.githubusercontent.com/78062156/134840316-4262949f-cd70-459b-beaa-aedf169ba47d.png)

I think that this is really interesting that you put cursive hand writing on there, I did the same thing when I was reading I had cursive next to me so I could digest the different ways and styles that were being written. I think the more you transcribe the easier it gets so keep trying its hard but it will get easier to read. I also found out that reading the pages before can help you understand the following pages.

**Comment by kmh6907** [comment]
<img width="1680" alt="transcription" src="https://user-images.githubusercontent.com/78093575/134965765-c76eeb66-22fb-4ae1-b8b2-1da89b09cd19.png">
I thought this homework assignment was really interesting but at the same time was a lot more complicated than I expected it to be. I wanted to challenge myself a bit so I chose a handwritten document. I was able to figure out a majority of the words but definitely not all of them. I found some of the words to be very unreadable because a few of them look like a bunch of jumbled lines. There are also some letters that resemble other letters and I wasn't able to figure out a word that would make sense for it. Some issues people might have with the reviewing process is the time it takes to go through and make sure all of the words, symbols, and transcriptions are correct. I feel like this is a very time-consuming process that not everyone has the patience or time for.

**Comment by NickyV1234** [comment]
![transcribing22](https://user-images.githubusercontent.com/70916831/135196206-ebcca219-b201-45ea-9ab3-742ec5c3c287.JPG)
![transcribing2](https://user-images.githubusercontent.com/70916831/135196215-6aea310e-0003-41fb-8d91-86f8922f2c45.JPG)

all that was really left was analyzing the audit logs. the transcribing of these was very weird because the format barely made any sense on the transcribing side. some transcribing didnt account for the fact that some pages were side by side and typed out one page and then transcribed the other page and put that below the other. however reading numbers was extremely easy. over all Id say this was just about as difficult the first time around

**Comment by SCD5363** [comment]
![Capture](https://user-images.githubusercontent.com/89928602/135646856-b1dd4eeb-7b33-4abf-b8ef-d0f744ac5864.PNG)

This seamed to be a leger with names and dates. It was very difficult to transcribe and understand what it said. I think that a couple of words were misspelled in the document
