### ISSUE TITLE
Long Night Transcription Event: November 9, 2021 (Extra Credit)

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#49]
For extra credit in DIGIT 100, 110, or 400, attend the Long Night Transcription Event on Tuesday November 9, 2021 between 11:30am and 3pm in Lilley Library 107. Participate in a live global transcription event coordinated at the same time around the world. For extra credit, record your impressions of the event here, and if possible, provide a screen capture or two to share a view of what you worked on. Comment here in this GitHub issue about the experience.

* Describe the experience of working with the documents, the interface provided or the kinds of documents you worked with.
* What could you see or glimpse about the lives of the people represented in the records you were working with? 
* What is it like to take part in a global memorial of the Long Night?

**Comment by bwm5473** [comment]
For the Transcription Event I was tasked with recording "change reports" from 1936 to 1945 in the Dachau concentration camp, where Nazi persecutees were imprisoned. I indexed names that were not covered in blue or gray shading; each name was accompanied by an Art der Haft (type of detention) prisoner number, a block number, and an Art der Veränderung (type of change
![Screenshot (4)](https://user-images.githubusercontent.com/70763198/140983309-2ce1e3d5-4b24-4c22-baca-a226d62d487f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/70763198/140983352-573cd237-1018-4a08-b614-abe93ae82758.png)
).

**Comment by san5281** [comment]
For the Transcription Event I worked on a portion of the list of prisoners' change reports at the Dachau concentration camps at Monday March 29, 1943 during WWII.  Through this small information, I was able to see that there were a mix of prisoners from both Germany and Poland. It is also true that some of these were able to escape, while many were transferred to Auschwitz. I learned a lot while working on this, primarily on the differences between Dachau and Auschwitz, and working on this memorial helps me understand the depths of this event.
![Everynamecounts](https://user-images.githubusercontent.com/70766362/140998271-46dac5cb-e1f7-4e85-b2d9-9c642af5f95c.PNG)

**Comment by Yuying-Jin** [comment]
My work was to record someone's personal information, such as date of birth and death, the religion, the relatives, and so on. At the beginning, I found struggled to locate information because of the language barrier. The instructor told me how to check the instruction for each blank, The instructions are clear and concise. Also, although the information was hand-written, it was legible, so the work was very easy.
![Capture1](https://user-images.githubusercontent.com/62861214/141012275-49cbfc4e-f65c-4938-bc23-4797c1c7dc1d.PNG)
![Capture2](https://user-images.githubusercontent.com/62861214/141012281-16e16cb9-4cd9-49eb-9148-68166f5d19b9.PNG)

**Comment by am0eba-byte** [comment]
I got to the event right when it started at 11:30, so I was able to sit and listen to the speakers' presentations as I transcribed some Personal Effects cards, which were small documents used to record the personal belongings that prisoners of the Holocaust were forced to hand over when they arrived at a concentration camp. As I transcribed, I listened in awe as multiple speakers from around the world explained the amazing digital archiving project Every Name Counts, which is a worldwide effort to preserve the millions of documents containing information about victims of the Holocaust by digitizing them. I couldn't stay very long, but I was able to transcribe 4 Personal Effects documents. Here's an example of one:

![example_of_transcription](https://user-images.githubusercontent.com/70165410/141028766-98662969-cde0-4317-88c6-82373739d81b.jpg)

As you worked through the different sections of the document, there were nifty links that provided explanations of each section of the document, for those who don't speak German. I recorded the occupations (Beruf) of the prisoners, their birthdates, where they were born, the names and relationships to their relatives (Anschrifts-Ort), the residence of the relative, the day the prisoner was admitted (Eingeliefert am), where they were admitted from (Eingeliefert von), the day the prisoner was released  (if applicable) (Entlassen am) and where they were released (normally, this meant that they were simply transferred to a different concentration camp, not actually "released"). You could also input information about the prisoner's death from the card, if there was any provided - but none of the cards I transcribed had any death information. Here's what the death information would look like: 

![date_of_death](https://user-images.githubusercontent.com/70165410/141029980-f5aec693-6102-4833-b80c-9eb3c0f34ecb.jpg)

Each prisoner also had a "prisoner category" on the top left of the document, which was typically whatever racial category the prisoner was (because, ya know, racism and antisemitism were the reasons why Nazis imprisoned people). For example, in my above screenshot, the prisoner's "category" was Ukrainer, meaning the person was Ukranian. 

Each time there was an umlaut (two dots) above a letter in a word I transcribed, I was instructed to put an "e" after the umlaut letter to transcribe it using an English keyboard:

![example_of_letterTranslation](https://user-images.githubusercontent.com/70165410/141030805-50c7f465-af9d-45dc-91cc-1c9d3c92433f.jpg)


Whenever I ran into an abbreviation I didn't understand in the document, I looked in the German abbreviation glossary book that was provided in the classroom - this is how I found out that the prefix "Krs." before the name of a location meant "district." 
 I also discovered that "KL." is the German abbreviation for "Konzentrationslager," which means "concentration camp."
 
 This was a super neat (although, at the same time, harrowing and melancholy) experience, and I'm so glad I went. I'm definitely going to do more of these transcriptions in my free time.

**Comment by kmh6907** [comment]
For the transcription event, (I forgot to take a picture) we got to work through different documents with names from the Dachau concentration camps. We would go through the documents and whatever was not highlighted in blue we would write down the prisoner number, first and last name, etc. I thought this was a really cool activity and I am glad I chose to attend even if it was for a short time. I found this to be similar to the assignments we did before where we had to transcribe the documents for the crowdsourcing exercises I believe. I thought this was definitely easier than those assignments though. Altogether it was a very unique event and I would like to attend something like this again in the future.
