### ISSUE TITLE
TEI Exercise 1

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#78]
Begin by reading these slides: ["Overview of Text Encoding and the TEI"](https://www.wwp.northeastern.edu/outreach/seminars/_current/presentations/overview/overview_newer_tutorial_00.xhtml) 

Then contribute a post to this conversation about learning the TEI. Please respond in your post to at least two of the following prompts:

* From what you're reading, how is writing TEI code similar to or different from what you've been doing with XML so far?
* What new things are you learning about representing documents in markup from these slides?
* On [one of the slides](https://www.wwp.northeastern.edu/outreach/seminars/_current/presentations/overview/overview_newer_tutorial_08.xhtml) the authors make an interesting statement about what TEI does:
"So although it looks as if what we’re doing here is **reproducing** a text, we are, in fact, selectively and strategically **modelling** it. We’re creating a surrogate or proxy, which functions sort of like a different projections of a map: each with selective and useful omissions and distortions. "
What do you think is the difference between reproducing and modeling in this statement and why might it be important to help us understand what we are doing when we describe documents using TEI and XML?

* Think about the documents or objects we looked at together in the library, and pick one that you remember really interested you. How do you think TEI could help you model something interesting about that document or object ? 

** Fun fact: one of the people who helped develop this slide deck is a member of our newtfire GitHub organization, @sydb . Other friends from the markup community who may be interested in our discussion include @djbpitt and @haggis78 .

**Comment by HadleighJae** [comment]
XML is an encoding language while TEI is the specifics of the XML encoding language. Both are used for marking up a specific text, but TEI is a specific syntax used in the XML markup. XML is very flexible while TEI is more specific.

Reproducing a text is just copying a text and replicating it. Modeling a text differs from simply reproducing a text because it is adding something new into the text. It includes more than what the text says on its own. It is another version of the text rather than the same text.

**Comment by TommyMC2** [comment]
I think the major difference between reproducing and modeling is reproducing it is as simple as copying and pasting you're just copying while to model it means to actively pick and choose not only what to keep and what to exclude but how to organize what you choose to keep.

I know sharing is going to be more and more important in this class and I just wonder what kind of conflicts we will see when things break and how we go about fixing it when we all have different approaches.

**Comment by ebeshero** [comment]
@TommyMC2 This is one reason we write schemas and/or work with an XML language with a controlled vocabulary like the TEI Guidelines. It helps to resolve conflicts, provide some guiding rules.

**Comment by josiahr21** [comment]
TEI is similar to XML as it provides a vocabullary that is used in markup text. This is a little different from what we have been doing in class so far as we have just been writing the syntax, rather than the actual language .

I have learned that the elements in TEI help shape the documents better, as it allows for breaks in the text. I also learned that TEI provides a deeper analysis of the text and is a better representation of the nested structure.

**Comment by Remdog712** [comment]
(Talking in a group project sense) It's very similar in the sense that rules don't have to be in place and no one can enforce them but once rules are offered, a group whether that be a small group or international, it leads to less confusion and systematic ways to classify and use documents.

I can see specifically on "Representing Research Objects," how closely the real document mirrors the digital and feels like there's no confusion on what the original would like if the page was forever lost except for the digital double. Kinda cool!

**Comment by VocaloidOtaku39** [comment]
I can tell that TEI is pretty much similar to XML, except for the fact that TEI is more advanced in analyzing the contents of a document, with advanced elements that are somewhat related to HTML projects, such as `<p>` and `<head>` . In XML, we basically wrap certain parts of text into different elements and attributes, but in TEI, the texts are deeply organized into more complex but flexible elements.

I have learned that TEI can also be used not just to analyze and model websites, but we can use it to analyze various kinds of documents, especially for research purposes. Also, when we use TEI for research purposes, we are using this to model the research in a more comprehensible way, especially with TEI's enhanced lexicon, making our research more organized.

I guess that TEI could be a helpful tool in analyzing, modeling, and organizing information from documents and converting them into digital files for online projects.

**Comment by TylerDollard** [comment]
TEI, or Text Encoding Initiative, shares similarities with XML in that it offers a structured vocabulary for marking up text. This marks a departure from our class, where we focused primarily on the syntax of writing, rather than the specific language or vocabulary used.

**Comment by GKon26** [comment]
TEI is sort of a type of XML, due to the similarities they have. Both can lead to similar places, but they are each their own thing. They also share similar markup, using <>, but the WAY they use them is vastly different. 

The difference between reproducing and modeling is one is, quite literally, reproducing the text onto a document. Whereas with modeling, you're taking everything about the document and writing it out. If there's a scratch out, a tear or a stain, it will all be "modeled" to give the most descriptive form of the document.

**Comment by creaturepsu** [comment]
TEI code is similar to XML because it nests elements in an organized manner which is also similar to html. If we were to have used TEI code for encoding the letters in our homework, it would have felt identical since we are taking big chunks of the text and breaking them down into parts. 
TEI is different though because it is specifically designed to model plays and other written works with its specific tags. In my opinion, TEI seems too similar to html and xml. Sure it has a richer vocabulary to describe things (and to model things) but can't we already do that with classes in html or attributes in xml? in one assignment I remember having to tag words which were covered or parts that were torn so it kind of of makes TEI seem extra if we can already do those things in xml.

**Comment by SonicSpaceFan025** [comment]
**Prompt 1**: Writing TEI code is similar to XML because both involve wrapping text into markup labels based on what concepts they identify as. XML defines concepts as syntax, while TEI defines them based on their structural characteristics such as paragraphs or headers.

**Prompt 2**: TEI is new to me, and one thing I learned that really stood out to me is that it works hand in hand with HTML, as the functions there are efficient in writing content in websites, such as using the `<p>` tag to write a paragraph of content, and the use of different vocabulary terms to identify certain parts of a document.

**Comment by 03lizchavez** [comment]
- [ TEI seems to be something that goes on before XML. They're similar but still have distinct features that differentiate the two. TEI is something that provides specifics to the encoding language and controlled vocab meanwhile XML has a syntax of encoding that basically distinguishing our markup (notes) from the content itself. They're similar in the sense that they both still deal with encoding that sorta of simplifies the content and depending on the file one wants it to be, it can lead to a PDF, RDF, MODS, and HTML. ]

- [ I'm learning the difference between HTML and TEI and the text encoding used and how TEI uses more information for the content meanwhile HTML loses information because it's trying to model a web page] 

- [I think the difference between producing and modeling is that with modeling, there's a structure in mind and it's kinda created to fit that specific "model" like maybe not including certain things like said later "omitting", compared to producing, everything is included and made to be exactly like the content. "Down to a T". ]

**Comment by lindseyxwood** [comment]
TEI Code is similar in how we organize our code. TEI separates different aspects of a document according to its importance in the source. The structure of the original document remains intact when coding this way.

One new thing I learned about the way TEI represents documents is that the TEI uses certain letters and words to constrain a document's description. This is because it is easier to use digitally.

The difference between reproducing and modeling is that reproducing is creating a new version while modeling is keeping the original document characteristics intact. It might be important to understand what we are doing when we are describing documents using TEI and XML because we are describing the author's/document's original structure.

**Comment by LPHerschell** [comment]
After viewing the slides, TEI code is similar to XML due to it being as to how we format our code. Although you are able to produce similar outcomes, the way that each one gets to that point is different.

Describing that something is "reproducing" a text would imply a direct copy, while "modeling" would involve more care and attention to form a strategic representation of the subject matter. This understanding is important when TEI and XML are used to describe documents since we are ensuring an effective representation suiting the intended analysis/study.

**Comment by MadisonSciarrillo** [comment]
According to what I've seen in the slides, TEI and XML are comparable in that they both use markup languages. However, TEI goes beyond XML's structural features. While XML primarily focuses on describing the hierarchy and structure of data, TEI goes a step further by offering standards and best practices designed expressly for textual document encoding. The representation of many characteristics of a text, including its content, structure, semantics, and even historical or editorial information, comprises specific, standardized components and attributes. TEI is essentially a more specific and expressive subset of XML made specifically for textual texts. So even though it appears that we are simply copying a text, we are actually carefully and deliberately modeling it, as stated in the statement. While modeling entails analyzing, structuring, and refining the text to achieve a specific goal, reproduction includes making an exact replica. We choose what information to include, how to structure it, and what context to provide when we model a text using TEI. We can produce representations of texts that are easier to access, more searchable, and valuable for numerous research and analysis tasks thanks to the modeling process. It's similar to making various maps, each stressing different aspects depending on the application.

**Comment by ceq5032** [comment]
XML is a syntax and is designed to record information about what something means. It defines a set of rules that is both  human readable and computer readable. TEI describes the characteristics of a certain text. TEI is the standard text encoding language that is used in the study of humanities.  TEI is more specific compared to XML. 

Reproducing is copying text into a document. The format of the original text doesn't change.  Modeling is more about telling about the actual document; such as a water mark being present and where it is present on the document. I think it's important to understand both methods so one can make a choice on how they want to encode the project. Some projects call for a looser syntax as others you might want a more structured syntax.

**Comment by cbl5678** [comment]
XML is a whole encoding language while TEI is the specific "language"  XML can use within the code. TEI is kind of like a schema in a sense. Both are used for marking up text, but XML is more flexible than TEI.

One thing im learning about representing documents is there is a uniform way to describe things, TEI, so any programmer looking at that code can read and understand it. TEI also helps get down to the specifics of describing things within the document for better representation than just any attribute.

**Comment by gylertaydos** [comment]
A little late to the party (my bad):

From what I understand, the TEI is similar to an XML schema because it has reserved elements that can hold specific data types, for the distinct purpose of modeling documents.

I didn't know that you could use HTML to do a document-structure-modeling thing before these slides, but frankly, I wouldn't have thought to try (I always think "webpage" when I think HTML).

I would say that reproducing a document is simply recreating it in a higher quality/more accessible/more usable version than its original. Modeling is more breaking down the document and organizing its contents. Both of which can make a document easier to read, but I suppose reproducing doesn't really add much as opposed to modeling.

**Comment by nhammer514** [comment]
The 'Text Encoding Initiative' format, or TEI is a specification for XML files that uses schema layout that enforces a layout that other TEI projects share and use. It uses a fixed vocabulary, structure, and elements that formats the XML files that use TEI. 

The Mark-Up programming languages have been proven to be extremely flexible and powerful. It is used in browsers through HTML, expresses data through standard XML, and TEI uses its own mark-up syntax to archive text documents. The TEI format is extremely important to the field of Digital Humanities, governing how archived documents should be laid out in order to be consistent through time and different projects.

**Comment by JordanJ7** [comment]
The TEI is similar to an XML schema because it has reserved elements that can hold specific data types, for the distinct purpose of modeling documents. It uses a fixed vocabulary, structure, and elements that formats the XML files that use TEI.     

 Reproducing quite literally, reproducing the text onto a document. Whereas with modeling, you're taking everything about the document and writing it out. Modeling is when there's a scratch out, a tear or a stain, it will all be modeled to give the most descriptive form of the document.

**Comment by lgmccurdy** [comment]
TEI provides the specifics for encoding language while XML defines the instructions for text encoding. Writing TEI code is similar to what we have been doing with XML so far in the sense that they are both kinds of markup languages and they both require the definition of elements and attributes. Some new things I am learning about representing documents in markup from these slides is that markup like TEI helps to preserve the structure of the text and allows documents to be structured in an organized manner.

**Comment by mew-II** [comment]
Though I don't think I fully understand TEI yet, I do think I somewhat understand its purpose. The thing that mainly stood out to me though was "The TEI is sustainable because it is standards-based and not dependent upon specific software or hardware." With the massive amount of software, hardware, and schema that exists around all the other coding languages, and devices I've seen and used, I do really like the idea that this one was designed to avoid that issue. I also believe one of the big parts of TEI is to add purpose to the text rather than just chop in into pieces and leave it as is. Adding understanding for those who come later to then be able to work off of rather than start at square one same as you did.

**Comment by hsosia1** [comment]
I am still new in learning TEI in its entirety, I believe that someday I will be able to know it more fully.According to what I've learned, TEI is designed to be readable by humans. While XML is not TEI, TEI is XML. Scholars can store, examine, and distribute textual data related to the humanities using the TEI, an XML-based markup language. TEI is a language that makes use of the syntax known as XML.They both call for the definition of the terms "elements" and "attributes." 

Reproducing a text is different from modeling it because it merely involves copying and duplicating it. Because it incorporates new information, modeling a text differs from merely copying it. When modeling, you take the entire document and lay it down in writing.
