### ISSUE TITLE
Can't push to sandbox

### ISSUE THREAD

**Issue by argynarg** [newtfire/textEncoding-Hub#9]
when I try to push I get this message

remote: Permission to newtfire/textEncoding-Hub.git denied to argynarg.
fatal: unable to access 'https://github.com/newtfire/textEncoding-Hub/': The requested URL returned error: 403

**Comment by ebeshero** [comment]
@argynarg Sorry I didn't see this until now! It has been the busiest, most laborious Labor Day ever! But I think I see the problem: You need to accept my invitation to join this repo so that you will have permission to push to it. I just sent you a fresh invitation: You want to check your email that you used to set up your GitHub account, and I think you'll see it. A few other students have yet to accept the invitation, so at this point that includes:
@argynarg
@bwm5473
@natalyamyers
@san5281
@thompsonjosh24
All of you: go check your email and accept my invitation so you can push to this repo! :-)

**Comment by bwm5473** [comment]
I am very sorry, but I did not notice the invitation in my email before it expired.

**Comment by ebeshero** [comment]
@bwm5473 Hang on! I'll send you another invitation right now. Make sure you check the email you used to create your GitHub account...

**Comment by ebeshero** [comment]
@bwm5473 Okay! I've just sent you a new invitation. Did you receive it? Click through to "accept" the invitation.

**Comment by bwm5473** [comment]
Yes. It's taken care of now, thank you very much.
